### PR TITLE
Added GriefPreventionPlus support

### PR DESCRIPTION
**Pull request by KaiKikuchi**

### CODE REVIEW

**Comment by thomas15v** [comment]
Do you have a devbukkit site for this plugin ? I can't find anything about it :).

**Comment by KaiKikuchi** [comment]
Nope. Just this: https://github.com/KaiKikuchi/GriefPreventionPlus

**Comment by thomas15v** [comment]
And what makes your changes so special that the normal griefprevention API will fail ? I am honestly interested, but I am against duplication :+1: .

**Comment by thomas15v** [comment]
Oh you changed the package name, ... . Hmmm Oke fine for me :).

**Comment by KaiKikuchi** [comment]
GP for MC1.7.10 is not supported anymore. There are too many changes so I think you can read everything here https://github.com/KaiKikuchi/GriefPreventionPlus and here https://github.com/KaiKikuchi/GriefPreventionPlus/blob/master/CHANGELOG.md

**Comment by thomas15v** [comment]
Oke. Good job. I will definally look at that plugin. Looks interesting for a GP Tekkit Lite server I want to make :). (I recently maded a mcpc 1.4.7 with bukkit 1.7.9 so I think it will work)

**Comment by KaiKikuchi** [comment]
Thank you! Feel free to report any issue!

**Pull request merged**
